### ISSUE TITLE
Feature request: optional rounding of output

### ISSUE THREAD

**Issue by peturdainn** [obrut/node-red-contrib-calculate#4]
Was very happy to finally find your module, I was looking for a rate-limiter that would output a rolling average but this will also do (maybe adding rolling average would make for a nice extra feature)

But my inputs are basically all integers so right now I need to add a function to round after it.

So it would be nice to have an option to round the output.
- checkbox option + round value
- improvement: number of decimals option to round to
- top improvement: detect number of decimals on input and round to that

Anyway, I already have an (untested) PR for the first option, may look at second and third improvements

**Comment by obrut** [comment]
As far as I understand rolling average would be interesting in a long running job, but node-red is not suitable for long history. Personally I orchestrate with node-red and use Chronograf/Grafana for history/trends, I also use the "real time" dashboard in node-red.
I use kind of a rolling average by chaining several calculate nodes. Using it for temperature sensors I create a one minute average, pass it on to ten minute average and then pass that on to one hour average. 
As for rounding I do round the data, but only for presentation and as late as possible to avoid rounding errors.
![image](https://user-images.githubusercontent.com/7264858/139260480-5dbcf64c-178e-4919-8104-ea8d84078b19.png)

**Comment by peturdainn** [comment]
My long history is not that long, but for example I have readings that come in every 10 seconds for real-time, and graph every minute or 5 minutes for a duration of 1 or 2 days.
But forget the rolling average ;)

I see you also have a round after the output, since I don't do chaining like you I wanted to let the calculate node do the rounding... Optional, that is...

**Comment by obrut** [comment]
I understand, but my view on node-red-nodes is simplicity, single purpose and chaining. I will not add your request to main, but let's keep the PR for others to use or fork.
There is a statistics node (node-red-contrib-statistics) with more functionality that might suit your specific needs, it was too complicated for me so I created this specialized one.
